[package]
name = "xhci"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["toku-sa-n <tokusan441@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.1"
os_units = "0.2.7"
pci_config = { git = "https://github.com/toku-sa-n/pci_config.git" }
x86_64 = "0.13.1"
